export const USER_RESPONSE = 'USER_RESPONSE';
export const IS_LOADING = 'IS_LOADING';
export const USER_RESPONSE_SUCCESS = 'USER_RESPONSE_SUCCESS';
export const USER_RESPONSE_FAILURE = 'USER_RESPONSE_FAILURE';